language: dart

dart:
  - dev
  - 2.0.0

dart_task:
  - test
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
    - dart: dev
      dart_task: dartfmt

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
