name: test_descriptor
version: 2.0.2-dev
description: An API for defining and verifying files and directory structures.
repository: https://github.com/dart-lang/test_descriptor

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  path: ^1.8.0
  term_glyph: ^1.2.0
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
