name: test_descriptor
version: 1.1.1
description: An API for defining and verifying directory structures.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/test_descriptor

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: '>=1.10.0 <3.0.0'
  collection: '^1.5.0'
  matcher: '^0.12.0'
  path: '^1.0.0'
  stack_trace: '^1.0.0'
  test: '>=0.12.19 <2.0.0'
  term_glyph: '^1.0.0'

dev_dependencies:
  pedantic: ^1.0.0
