name: test_descriptor
version: 2.0.0-nullsafety.1-dev
description: An API for defining and verifying directory structures.
homepage: https://github.com/dart-lang/test_descriptor

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  async: ^2.5.0-nullsafety
  collection: ^1.15.0-nullsafety
  matcher: ^0.12.10-nullsafety
  path: ^1.8.0-nullsafety
  term_glyph: ^ 1.2.0-nullsafety
  test: ^1.16.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
