name: test_descriptor
version: 1.2.1-dev
description: An API for defining and verifying directory structures.
homepage: https://github.com/dart-lang/test_descriptor

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  archive: '^2.0.0'
  async: '>=1.13.0 <3.0.0'
  collection: '^1.5.0'
  matcher: '^0.12.0'
  meta: '^1.1.7'
  path: '^1.0.0'
  stack_trace: '^1.0.0'
  test: '^1.6.0'
  term_glyph: '^1.0.0'

dev_dependencies:
  pedantic: ^1.0.0
